spring.application.name=servicio-donaciones
server.port=8080

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

logistica.proveedores.propia-url=${LOGISTICA_PROPIA_URL:http://localhost:8083}
logistica.proveedores.alternativa-url=${LOGISTICA_ALTERNATIVA_URL:https://tp-anual-dsi-grupo4-1.onrender.com}
logistica.broker.estrategia=${LOGISTICA_BROKER_ESTRATEGIA:ROUND_ROBIN}
logistica.eventos.poll-delay-ms=60000
