spring.application.name=servicio-donaciones
server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
