spring.application.name=servicio-donaciones
server.port=8080

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

logistica.proveedores.propia-url=${LOGISTICA_PROPIA_URL:http://localhost:8083}
logistica.proveedores.alternativa-url=${LOGISTICA_ALTERNATIVA_URL:https://tp-anual-dsi-grupo4-1.onrender.com}
logistica.broker.estrategia=${LOGISTICA_BROKER_ESTRATEGIA:ROUND_ROBIN}
logistica.eventos.poll-delay-ms=60000
logistica.envio.cron=0 30 2 * * *

incentivos.base-url=${INCENTIVOS_BASE_URL:http://localhost:8081}

donantes.inactividad.cron=0 0 4 * * *

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
